version: "3"

services:
  bot-1:
    image: noisy-bot
    container_name: instagram-telegram-bot
    build: ./
    depends_on:
      - mongo
    env_file: 
      - .env

  mongo:
    image: mongo:latest
    command: [--auth]
    volumes: 
      - mongo_volume:/data/db
    restart: always

networks:
  bot-app:
    driver: bridge


volumes: 
  mongo_volume: