version: "3"

services:
  bot:
    image: noisy-bot
    build: ./
    depends_on:
      - mongo
    env_file: 
      - .env

  mongo:
    image: mongo:latest
    command: [--auth]
    volumes: 
      - mongo_volume:/data/db
    restart: always
    ports: 
      - 27017:27017

networks:
  bot-app:
    driver: bridge


volumes: 
  mongo_volume: